spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trungdvsmartosc/config-server-demo
          clone-on-start: true

server:
  port: 8888
